import './globals.css';
import type { Metadata } from 'next';
import { Pretendard } from '@/assets';
import { CartSidebar } from '@/components/cart';
import { Footer, Header } from '@/components/layout';
import { RTKProvider, CartProvider } from '@/components/providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={`${Pretendard.variable} font-sans`}>
        <RTKProvider>
          <CartProvider>
            <Header />
            <CartSidebar />
            <main>{children}</main>
            <Footer />
          </CartProvider>
        </RTKProvider>
      </body>
    </html>
  );
}
