import './globals.css';
import type { Metadata } from 'next';
import { Pretendard } from '@/assets';
import { CartSidebar } from '@/components/cart';
import { Footer, Header } from '@/components/layout';
import { RTKProvider, CartProvider, ThemeProvider } from '@/components/providers';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en' suppressHydrationWarning>
      <body className={`${Pretendard.variable} font-sans`}>
        <ThemeProvider defaultTheme='system' attribute='class' enableSystem>
          <RTKProvider>
            <CartProvider>
              <Header />
              <CartSidebar />
              <main>{children}</main>
              <Footer />
            </CartProvider>
          </RTKProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
